from zexporta.config import (
    CHAINS_CONFIG,
    DKG_JSON_PATH,
    DKG_NAME,
    EVM_WITHDRAWER_PRIVATE_KEY,
    SA_SHIELD_PRIVATE_KEY,
    SENTRY_DNS,
)

LOGGER_PATH = "/var/log/withdraw/"
WITHDRAW_DELAY_SECOND = 10
SA_TIMEOUT = 60
SA_DELAY_SECOND = 20
