from zex_deposit.config import (
    CHAINS_CONFIG,
    DKG_JSON_PATH,
    DKG_NAME,
    SA_SHIELD_PRIVATE_KEY,
    SENTRY_DNS,
    WITHDRAWER_PRIVATE_KEY,
)

LOGGER_PATH = "/var/log/withdraw/"
WITHDRAW_DELAY_SECOND = 120
SA_TIMEOUT = 60
SA_DELAY_SECOND = 60
